admin_homepage:
    path:     /Home
    defaults: { _controller: AdminBundle:Default:index }
admin_listPosts:
    path:     /Posts
    defaults: { _controller: AdminBundle:Post:Listposts }
Admin_deletePost:
    path:     /deletepost/{postId}
    defaults: { _controller: AdminBundle:Post:Delete }
Admin_UpdatePost:
    path:     /UpdatePost/{postId}
    defaults: { _controller: AdminBundle:Post:Update }
