<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIhf15ws\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIhf15ws/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIhf15ws.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIhf15ws\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIhf15ws\appDevDebugProjectContainer([
    'container.build_hash' => 'Ihf15ws',
    'container.build_id' => '7c703737',
    'container.build_time' => 1553029184,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIhf15ws');
