<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEuoqvzy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEuoqvzy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEuoqvzy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEuoqvzy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEuoqvzy\appDevDebugProjectContainer([
    'container.build_hash' => 'Euoqvzy',
    'container.build_id' => '7cd43373',
    'container.build_time' => 1552996823,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEuoqvzy');
